BUILD_OUTPUT=.
CFLAGS += -g -Wall -I./inc
CFLAGS_SELFTEST += ${CFLAGS} -DSELF_TEST

LDFLAGS += -L${BUILD_OUTPUT}
LDFLAGS_SELFTEST += ${LDFLAGS} -Wl,-O1 -Wl,--hash-style=gnu -Wl,--no-as-needed -lmemfnswrap -Wl,--as-needed


default: lib link bin

selftest: selftestlib link selftestbin

lib:
	$(CC) $(CFLAGS) lib/memfns_wrap.c -o ${BUILD_OUTPUT}/memfns_wrap.o -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -c -fPIC 
	$(CC) $(LDFLAGS) ${BUILD_OUTPUT}/memfns_wrap.o -lrt -ldl -shared -Wl,-soname,libmemfnswrap.so.0 -o ${BUILD_OUTPUT}/libmemfnswrap.so.0.0

bin:
	$(CC) $(CFLAGS) -c uty/memleakutil.c -o ${BUILD_OUTPUT}/memleakutil.o
	$(CC) $(LDFLAGS) ${BUILD_OUTPUT}/memleakutil.o -lpthread -lrt -ldl -o ${BUILD_OUTPUT}/memleakutil

selftestlib:
	$(CC) $(CFLAGS_SELFTEST) lib/memfns_wrap.c -o ${BUILD_OUTPUT}/memfns_wrap.o -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -c -fPIC 
	$(CC) $(LDFLAGS) ${BUILD_OUTPUT}/memfns_wrap.o -lrt -ldl -shared -Wl,-soname,libmemfnswrap.so.0 -o ${BUILD_OUTPUT}/libmemfnswrap.so.0.0

selftestbin:
	$(CC) $(CFLAGS_SELFTEST) -c uty/memleakutil.c -o ${BUILD_OUTPUT}/memleakutil.o
	$(CC) $(CFLAGS_SELFTEST) -c tst/memleakutil_test.c -o ${BUILD_OUTPUT}/memleakutil_test.o
	$(CC) $(LDFLAGS_SELFTEST) ${BUILD_OUTPUT}/memleakutil.o ${BUILD_OUTPUT}/memleakutil_test.o -lpthread -lrt -ldl -o ${BUILD_OUTPUT}/memleakutil

link:
	cd ${BUILD_OUTPUT}
	ln -sf libmemfnswrap.so.0 libmemfnswrap.so
	ln -sf libmemfnswrap.so.0.0 libmemfnswrap.so.0

clean:
	rm -f libmemfnswrap.so* memleakutil memleakutil.o memfns_wrap.o memleakutil_test.o


